### ISSUE TITLE
What is the goal of that library ?

### ISSUE THREAD

**Issue by shulard** [hoaproject/Model#5]
Hello!

It's more a question than a real issue.
As I already said on IRC, I'm currently working on an ActiveRecord library here: https://gitlab.com/bee4/activerecord

I'm a little lost in my patterns choices. I've found that lib which seems to represent a kind of ActiveRecord model (handle entity persistence through `save`). Maybe I'm wrong...

What are the goals of that lib ? Is it a project which need to be forgotten or is it possible to make it evolve ?

[Reddit](https://www.reddit.com/r/PHP/comments/3mzk9j/need_review_creation_of_a_dbal_library_which_is/) give me a great ressource here : http://www.mehdi-khalili.com/orm-anti-patterns-series/
It is about ORM implementations (and Active Record). I think that there are some good points to take here... If you think that this lib can go forward, I'll be really glad to be part of it :smile:

**Comment by Jir4** [comment]
`Is it a project which need to be forgotten`
YES !

**Comment by Hywan** [comment]
@Jir4 :+1:
@shulard The more we go further with this library, the less I know what to do with it. I like the implementation of “models” in Ember, this is like an active record. So `Hoa\Model` might be an active record. However, the more I learn about active record, the less I think this is a good direction.

What's your opinion about active record?

**Comment by shulard** [comment]
Hello @Hywan,

I'm in the same situation, the more I learn about Active Record and the less I think it's the best pattern here...

I don't tell that it's a never to use pattern but it's powerful in a very limited set of cases :

* Throwable code which handle data layer
* Very simple application with entity = form data = db row

I think that a library like the current `Hoa\Model` is a nice abstraction but the SRP violation inducted by Active Record can be a problem for maintainability.

Maybe a nice approach can be :

* Transform that lib to a SRP valid model representation (like that all the concepts - relations, indexes, properties... are represented and can then be used for a specific DBAL implementation)
* Develop implementations on that abstractions for common cases : Relational, NoSQL
* Implement a generic `Query Builder` which can use that models to create requests

Today I found that it miss a library which can handle most of the DB types. OOP can be used as a bridge between the application and the data because, most of the time, tools capabilities can be implemented.

For me a new `Hoa\Model` can be a generic `Persistence Model` layer... Though ?

**Comment by Hywan** [comment]
Do you know model design in Ember? That's almost like an active record but they call the `save`, `update`, `delete` etc. methods on an adapter. This is how `Hoa\Model` works since the beginning, and I think this is how we must do things.

However, having a “generic” query builder has no meaning for me. Querying something requires a specific language and more importantly: Specific theory. For SQL, this is the **set theory**. For NoSQL, maybe this is something else. For ElasticSearch, this is again another “theory”. So having something generic would imply a subset of the theory, and so there is no particular interest :-(. Thoughts?
